[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'lambdalisue/suda.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'bling/vim-airline'
hook_add = '''
  set laststatus=2
'''

[[plugins]]
repo = 'thinca/vim-qfreplace'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  let g:quickrun_config = {
  \    '_': {
  \      'runner': 'vimproc',
  \      'runner/vimproc/updatetime': 60,
  \    },
  \    'tex': {
  \      'command': 'latexmk',
  \      'exec': '%c -pdfdvi %s',
  \    },
  \  }
'''

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'vim-jp/vim-cpp'
on_ft = 'cpp'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = 'javascript'

[[plugins]]
repo = 'chikamichi/mediawiki.vim'
on_ft = 'mediawiki'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'maralla/vim-toml-enhance'
on_ft = 'toml'

[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = 'plantuml'

[[plugins]]
repo = 'rhysd/vim-clang-format'
hook_add = '''
  let g:clang_format#command = 'clang-format'
  let g:clang_format#code_style = 'llvm'
  let g:clang_format#style_options = {
    \ 'AllowShortFunctionsOnASingleLine': 'None',
    \ 'PointerAlignment': 'Left'}
  autocmd FileType c,cpp,objc nnoremap <buffer><Leader>cf :<C-u>ClangFormat<CR>
  autocmd FileType c,cpp,objc vnoremap <buffer><Leader>cf :ClangFormat<CR>
  nmap <Leader>C :ClangFormatAutoToggle<CR>
'''

[[plugins]]
repo = 'fatih/vim-go'
rev = 'master'
on_ft = 'go'

[[plugins]]
repo = 'rhysd/committia.vim'
